# Generated by Django 5.2.1 on 2025-05-17 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
        ("data_integration", "0002_externaldatasource_error_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="external_source",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to an external data source",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="data_integration.externaldatasource",
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Upload a CSV file or leave empty if using an external data source",
                null=True,
                upload_to="data_sources/",
            ),
        ),
    ]
