# Generated by Django 5.2.1 on 2025-05-18 00:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_datasource_external_source_alter_datasource_file"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chatsession",
            unique_together={("session_id", "data_source")},
        ),
    ]
