# Generated by Django 5.2.1 on 2025-05-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaldatasource",
            name="error_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="externaldatasource",
            name="last_error",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="externaldatasource",
            name="sync_interval",
            field=models.IntegerField(
                default=3600,
                help_text="Sync interval in seconds. Default is 3600 (1 hour)",
            ),
        ),
        migrations.AddField(
            model_name="externaldatasource",
            name="timeout",
            field=models.IntegerField(
                default=300,
                help_text="Timeout in seconds for each sync operation. Default is 300 (5 minutes)",
            ),
        ),
        migrations.AlterField(
            model_name="externaldatasource",
            name="api_url",
            field=models.URLField(default="https://proto.notso.ai/jumbo/chats"),
        ),
    ]
